### ISSUE TITLE
Throw "custom Exception" instead of "\RuntimeException" when “No manager is defined for an index"

### ISSUE THREAD

**Issue by jigante** [sineflow/ElasticsearchBundle#4]
It would be useful to have a **custom Exception** instead of **\RuntimeException** thrown when “No manager is defined for an index"
https://github.com/sineflow/ElasticsearchBundle/blob/master/Manager/IndexManagerRegistry.php#L55

In this way would be possible for example in our migration system to avoid a fatal error when we remove the configuration to manage an index that we do not use anymore, but one of the previous migrations tries to mark as to be rebuilt.

**Comment by pmishev** [comment]
https://github.com/sineflow/ElasticsearchBundle/commit/5c8155a650eeed47f1d27e470c467b6f710b04ae
